<?php
define('END_CONTROLLER_DIR','end_admin/controller/');
define('END_VIEWER_DIR','end_admin/view/');
define('END_LANGUAGE_DIR','end_admin/language/');
define('END_MODULE_DIR','end_admin/');
define('END_MODULE','admin');
chdir('end_system');
include("index.php");
?>